---
name: Docker Image CI

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  schedule:  # Run every Monday at 15:00
    - cron: '0 15 * * 1'
  workflow_dispatch:

concurrency:
  group: "${{github.repository}}-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: tlan16/openconnect:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tlan16/openconnect
          short-description: 'AnyConnect, Pulse and PAN container with proxies'
      - uses: gautamkrishnar/keepalive-workflow@1.1.0
